# Generated by Django 4.2.5 on 2023-10-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='periodicity',
            field=models.CharField(choices=[('DAILY', 'ежедневно'), ('WEEKLY', 'еженедельно'), ('MONTHLY', 'ежемесячно')], max_length=50, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body_letter',
            field=models.TextField(verbose_name='Содержание рассылки'),
        ),
    ]
